[theme]
primaryColor="#7A3E48"              # vino profundo
backgroundColor="#FAF7F2"          # blanco cálido
secondaryBackgroundColor="#EDE6DD" # beige suave
textColor="#2B2B2B"
font="serif"
#codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
